source 'https://github.com/CocoaPods/Specs'
use_frameworks!

target 'ThirdPartyMailerExample' do
  pod 'ThirdPartyMailer', :path => '../'
end

target 'ThirdPartyMailerTests' do
  pod 'ThirdPartyMailer', :path => '../'
end

